config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root "posts#index"
  get 'about', to: 'pages#about'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  # Active Storage
  has_one_attached :thumbnail
  has_one_attached :banner
  
  # Action text rails 6
  has_rich_text :body

  validates :title, length: {minimum: 5}
  validates :body, length: {minimum: 25}

  self.per_page = 10

  extend FriendlyId
  friendly_id :title, use: :slugged

  def optimized_image(image, x, y)
    return image.variant(resize_to_fill: [x, y]).processed
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def username
    return email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :is_admin!

    private
    def is_admin!
        if current_user && current_user
        else
            redirect_to root_path
        end
    end    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_admin!, except: [:index, :show]
  # GET /posts or /posts.json
  def index
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page])
  end

  # GET /posts/1 or /posts/1.json
  def show
    views = @post.views + 1
    @post.update(views: views)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :thumbnail, :banner)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_alert.html.erb
<br>
<br>
<br>
<div class='container'>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="<%= root_path %>">BLOG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= about_path %>">About</a>
      </li>

    </ul>
    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false"><%= current_user.username %></a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.admin %>
              <a class="dropdown-item" href="<%= new_post_path %>">New Post</a>
            <% end %>
            <a class="dropdown-item" href="<%= edit_user_registration_path %>">Account Settings</a>
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class:'dropdown-item' %>
          </div>
        </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Signup", new_user_registration_path, class:'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to "Signin", new_user_session_path, class:'nav-link' %>
      </li>

      <% end %>

    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <br>
    <% if notice%>
      <%= render 'layouts/alert' %>
    <% end %>
    <br>
    <br>
    <%= yield %>
    <br>
  </body>
</html>

app/views/pages/about.html.erb
<div class='container'>
    <div class="jumbotron">
        <h1 class="display-4">About Me</h1>
        <br>
        <div class='row'>
            <p style="text-align: justify">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua. Et tortor at risus viverra adipiscing at in tellus. Risus feugiat in ante metus
                dictum. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Maecenas pharetra
                convallis posuere morbi leo urna molestie. Ornare massa eget egestas purus. Nam aliquam sem et tortor.
                Porttitor rhoncus dolor purus non enim praesent. Laoreet id donec ultrices tincidunt. Urna condimentum
                mattis pellentesque id nibh tortor. Ullamcorper a lacus vestibulum sed. Leo a diam sollicitudin tempor
                id eu nisl nunc. Quisque non tellus orci ac auctor augue mauris. A cras semper auctor neque vitae tempus
                quam pellentesque nec. Non diam phasellus vestibulum lorem sed. In nisl nisi scelerisque eu ultrices
                vitae auctor eu augue. Consequat ac felis donec et odio pellentesque. Ac tortor dignissim convallis
                aenean et. Ultricies integer quis auctor elit sed. Consequat nisl vel pretium lectus quam id.
                <br>
                <br>
                Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Blandit massa enim nec dui
                nunc. Pellentesque id nibh tortor id aliquet lectus. Auctor elit sed vulputate mi sit. Netus et
                malesuada fames ac turpis egestas integer eget. Nunc sed velit dignissim sodales ut. Pellentesque elit
                ullamcorper dignissim cras tincidunt lobortis feugiat. Tortor at auctor urna nunc. Phasellus vestibulum
                lorem sed risus ultricies tristique nulla. In pellentesque massa placerat duis ultricies lacus sed. Urna
                nec tincidunt praesent semper feugiat nibh sed pulvinar.
            </p>
        </div>
        <div class="btn-group" role="group" aria-label="Basic example">
            <button type="button" onclick="window.open('https://github.com/Aslanbayli');"
                class="btn btn-secondary">GitHub</button>
            <button type="button" class="btn btn-secondary">Middle</button>
            <button type="button" class="btn btn-secondary">Right</button>
        </div>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>

  <div class="form-inputs">
  <%= f.label :title, class:'form-control'%>
    <%= f.text_field :title, class:'form-control string' %>
    <%= f.label :thumbnail, class:'form-control'%>
    <%= f.file_field :thumbnail %>
    <%= f.label :banner, class:'form-control'%>
    <%= f.file_field :banner %>
    <%= f.label :content, class:'form-control'%>
    <%= f.rich_text_area :body %>
    <%#= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>
<br>
<%= link_to 'Show', @post, class:"btn btn-secondary"  %>
<%= link_to 'Back', posts_path, class:"btn btn-secondary"  %>

app/views/posts/index.html.erb
<div class='container'>

  <% @posts.each do |post|%>
    <div class="row">
      <div class='card mb-3'>
        <img class="card-img-top", src="<%= url_for(post.optimized_image(post.thumbnail, 586, 180))%>", alt="Blog Post Image Card" />
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to post.title, post%>
          </h5>
          <p class='card-text'>
            <%= post.body.to_plain_text.truncate_words(50) %>
          </p>
          <p class='card-text'>
            <small class='text-muted'>
              <%= post.updated_at.strftime("%A, %B %e, %Y") %> by <%= post.user.username %> | <%= pluralize(post.views, "View") %>
            </small>
          </p>

          <% if current_user %>
            <% if current_user.admin %>
              <p>
                <%= link_to("Destroy", post, :method => :delete, :confirm => "Are you sure?") %> | 
                <%= link_to "Edit", edit_post_path(post) %>
              </p>
            <% end %>
          <% end %>

        </div>
      </div>
    </div>
  <% end %>

  <div clas="row">
    <div class='apple_pagination '>
      <%= will_paginate @posts, :container => false %>
    </div>
  </div>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>
<br>
<%= link_to 'Back', posts_path, class:"btn btn-secondary" %>

app/views/posts/show.html.erb
<div style="width: 100%; height: 300px; overflow-y: hidden">
  <%= image_tag(@post.banner, style:'width: 100%;') %>
</div>

<div class='container' style="margin-top: 2em">
  <div class='row'>
    <div class=jumbotron style='width: 100%'>
      <h1 class="display-4">
        <%= link_to @post.title, root_path%>
      </h1>
      <p class='lead'>
        <%= @post.updated_at.strftime("%A, %B %e, %Y") %> by <%= @post.user.username %> | <%= pluralize(@post.views, "View") %>
      </p>
      <hr class="my-4">
      <div class="post-body">
        <%= @post.body %>
      </div>
    </div>
  </div>

<%= link_to 'Edit', edit_post_path(@post), class:"btn btn-secondary" %>
<%= link_to 'Back', posts_path, class:"btn btn-secondary" %>

</div>